(defun tty/runlength-compression (list)
  (let (pack)
    (while (consp list)
      (let* ((item (pop list))
	     (nest (list item))
	     (cntr 1))
        (while (equal item (car list))
          (pop list)
          (setq cntr (+ cntr 1)))
	(push cntr nest)
        (push nest pack)))
    (nreverse pack)))

(tty/runlength-compression '(a a a a b c c a a d e e e e))
;; => ((4 a) (1 b) (2 c) (2 a) (1 d) (4 e))
