(defun tty/runlength-decompression (list)
  (let (decoded)
    (while (consp list)
      (let ((head (pop list)))
	(if (consp head)
	    (let ((cntr (car head)))
	      (while (> cntr 0)
		(setq cntr (- cntr 1))
		(push (cadr head) decoded)))
	  (push head decoded))))
    (nreverse decoded)))

(tty/runlength-decompression '((4 a) b (2 c) (2 a) d (4 e)))
;; => (a a a a b c c a a d e e e e)
